# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tozadore/Projects/Architecture_v2_0/Arch_2_1/GUI/meeting.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(474, 612)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_62 = QtGui.QFrame(Dialog)
        self.frame_62.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_62.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_62.setObjectName(_fromUtf8("frame_62"))
        self.gridLayout_53 = QtGui.QGridLayout(self.frame_62)
        self.gridLayout_53.setObjectName(_fromUtf8("gridLayout_53"))
        self.label_212 = QtGui.QLabel(self.frame_62)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_212.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.label_212.setFont(font)
        self.label_212.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_212.setAlignment(QtCore.Qt.AlignCenter)
        self.label_212.setObjectName(_fromUtf8("label_212"))
        self.gridLayout_53.addWidget(self.label_212, 0, 0, 1, 3)
        self.verticalLayout.addWidget(self.frame_62)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_20 = QtGui.QFrame(Dialog)
        self.frame_20.setFrameShape(QtGui.QFrame.Box)
        self.frame_20.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_20.setObjectName(_fromUtf8("frame_20"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout(self.frame_20)
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.wd_label = QtGui.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.wd_label.setFont(font)
        self.wd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wd_label.setObjectName(_fromUtf8("wd_label"))
        self.horizontalLayout_32.addWidget(self.wd_label)
        self.label_278 = QtGui.QLabel(self.frame_20)
        self.label_278.setMaximumSize(QtCore.QSize(13, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_278.setFont(font)
        self.label_278.setAlignment(QtCore.Qt.AlignCenter)
        self.label_278.setObjectName(_fromUtf8("label_278"))
        self.horizontalLayout_32.addWidget(self.label_278)
        self.md_label = QtGui.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.md_label.setFont(font)
        self.md_label.setAlignment(QtCore.Qt.AlignCenter)
        self.md_label.setObjectName(_fromUtf8("md_label"))
        self.horizontalLayout_32.addWidget(self.md_label)
        self.label_276 = QtGui.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_276.setFont(font)
        self.label_276.setAlignment(QtCore.Qt.AlignCenter)
        self.label_276.setObjectName(_fromUtf8("label_276"))
        self.horizontalLayout_32.addWidget(self.label_276)
        self.month_label = QtGui.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.month_label.setFont(font)
        self.month_label.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label.setObjectName(_fromUtf8("month_label"))
        self.horizontalLayout_32.addWidget(self.month_label)
        self.label_277 = QtGui.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_277.setFont(font)
        self.label_277.setAlignment(QtCore.Qt.AlignCenter)
        self.label_277.setObjectName(_fromUtf8("label_277"))
        self.horizontalLayout_32.addWidget(self.label_277)
        self.year_label = QtGui.QLabel(self.frame_20)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.year_label.setFont(font)
        self.year_label.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label.setObjectName(_fromUtf8("year_label"))
        self.horizontalLayout_32.addWidget(self.year_label)
        self.verticalLayout.addWidget(self.frame_20)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.HLine)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.place_lineEdit = QtGui.QLineEdit(self.frame)
        self.place_lineEdit.setObjectName(_fromUtf8("place_lineEdit"))
        self.gridLayout.addWidget(self.place_lineEdit, 5, 6, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.dateEdit = QtGui.QDateEdit(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(132, 132, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(132, 132, 132))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.dateEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateEdit.setFont(font)
        self.dateEdit.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.gridLayout.addWidget(self.dateEdit, 5, 2, 1, 1)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 4, 6, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 5, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 7, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.period_lineEdit = QtGui.QLineEdit(self.frame)
        self.period_lineEdit.setObjectName(_fromUtf8("period_lineEdit"))
        self.gridLayout.addWidget(self.period_lineEdit, 0, 6, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 3, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 2, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 1, 2, 1, 1)
        self.timeEdit = QtGui.QTimeEdit(self.frame)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.gridLayout.addWidget(self.timeEdit, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.calendarWidget = QtGui.QCalendarWidget(Dialog)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setHorizontalHeaderFormat(QtGui.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.verticalLayout.addWidget(self.calendarWidget)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.textEdit = QtGui.QTextEdit(Dialog)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.calendarWidget, QtCore.SIGNAL(_fromUtf8("clicked(QDate)")), self.dateEdit.setDate)
        QtCore.QObject.connect(self.dateEdit, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.calendarWidget.setSelectedDate)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.timeEdit, self.period_lineEdit)
        Dialog.setTabOrder(self.period_lineEdit, self.dateEdit)
        Dialog.setTabOrder(self.dateEdit, self.place_lineEdit)
        Dialog.setTabOrder(self.place_lineEdit, self.calendarWidget)
        Dialog.setTabOrder(self.calendarWidget, self.textEdit)
        Dialog.setTabOrder(self.textEdit, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_212.setText(_translate("Dialog", "Test Details", None))
        self.wd_label.setText(_translate("Dialog", "Monday", None))
        self.label_278.setText(_translate("Dialog", ",", None))
        self.md_label.setText(_translate("Dialog", "02", None))
        self.label_276.setText(_translate("Dialog", "of", None))
        self.month_label.setText(_translate("Dialog", "October", None))
        self.label_277.setText(_translate("Dialog", "of", None))
        self.year_label.setText(_translate("Dialog", "2019", None))
        self.label.setText(_translate("Dialog", "Time", None))
        self.label_4.setText(_translate("Dialog", "Date", None))
        self.label_3.setText(_translate("Dialog", "Place", None))
        self.label_2.setText(_translate("Dialog", "Period", None))
        self.label_5.setText(_translate("Dialog", "Details", None))

