# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tozadore/Projects/Architecture_v2_0/Arch_2_1/GUI/system_variables_control.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(380, 391)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.filePathLineEdit = QtGui.QLineEdit(Dialog)
        self.filePathLineEdit.setObjectName(_fromUtf8("filePathLineEdit"))
        self.gridLayout.addWidget(self.filePathLineEdit, 2, 1, 1, 1)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formFrame = QtGui.QFrame(self.frame)
        self.formFrame.setObjectName(_fromUtf8("formFrame"))
        self.formLayout = QtGui.QFormLayout(self.formFrame)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.versionLabel = QtGui.QLabel(self.formFrame)
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName(_fromUtf8("versionLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.versionLabel)
        self.versionSpinBox = QtGui.QSpinBox(self.formFrame)
        self.versionSpinBox.setMaximum(100000)
        self.versionSpinBox.setObjectName(_fromUtf8("versionSpinBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.versionSpinBox)
        self.userIdLabel = QtGui.QLabel(self.formFrame)
        self.userIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.userIdLabel.setObjectName(_fromUtf8("userIdLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.userIdLabel)
        self.userIdSpinBox = QtGui.QSpinBox(self.formFrame)
        self.userIdSpinBox.setMaximum(100000)
        self.userIdSpinBox.setObjectName(_fromUtf8("userIdSpinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.userIdSpinBox)
        self.evaluationIdLabel = QtGui.QLabel(self.formFrame)
        self.evaluationIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.evaluationIdLabel.setObjectName(_fromUtf8("evaluationIdLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.evaluationIdLabel)
        self.evaluationIdSpinBox = QtGui.QSpinBox(self.formFrame)
        self.evaluationIdSpinBox.setMaximum(100000)
        self.evaluationIdSpinBox.setObjectName(_fromUtf8("evaluationIdSpinBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.evaluationIdSpinBox)
        self.interactionIdLabel = QtGui.QLabel(self.formFrame)
        self.interactionIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.interactionIdLabel.setObjectName(_fromUtf8("interactionIdLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.interactionIdLabel)
        self.interactionIdSpinBox = QtGui.QSpinBox(self.formFrame)
        self.interactionIdSpinBox.setMaximum(100000)
        self.interactionIdSpinBox.setObjectName(_fromUtf8("interactionIdSpinBox"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.interactionIdSpinBox)
        self.sessionIdLabel = QtGui.QLabel(self.formFrame)
        self.sessionIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sessionIdLabel.setObjectName(_fromUtf8("sessionIdLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.sessionIdLabel)
        self.sessionIdSpinBox = QtGui.QSpinBox(self.formFrame)
        self.sessionIdSpinBox.setMaximum(100000)
        self.sessionIdSpinBox.setObjectName(_fromUtf8("sessionIdSpinBox"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.sessionIdSpinBox)
        self.label_2 = QtGui.QLabel(self.formFrame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.groupevalIdSpinBox = QtGui.QSpinBox(self.formFrame)
        self.groupevalIdSpinBox.setMaximum(100000)
        self.groupevalIdSpinBox.setObjectName(_fromUtf8("groupevalIdSpinBox"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.groupevalIdSpinBox)
        self.label_4 = QtGui.QLabel(self.formFrame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_4)
        self.meetingIdSpinBox = QtGui.QSpinBox(self.formFrame)
        self.meetingIdSpinBox.setObjectName(_fromUtf8("meetingIdSpinBox"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.meetingIdSpinBox)
        self.horizontalLayout.addWidget(self.formFrame)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 2)
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(False)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.buttonBox, self.filePathLineEdit)
        Dialog.setTabOrder(self.filePathLineEdit, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.versionSpinBox)
        Dialog.setTabOrder(self.versionSpinBox, self.userIdSpinBox)
        Dialog.setTabOrder(self.userIdSpinBox, self.evaluationIdSpinBox)
        Dialog.setTabOrder(self.evaluationIdSpinBox, self.interactionIdSpinBox)
        Dialog.setTabOrder(self.interactionIdSpinBox, self.sessionIdSpinBox)
        Dialog.setTabOrder(self.sessionIdSpinBox, self.groupevalIdSpinBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_3.setText(_translate("Dialog", "File Path:", None))
        self.versionLabel.setText(_translate("Dialog", "Version", None))
        self.userIdLabel.setText(_translate("Dialog", "User id", None))
        self.evaluationIdLabel.setText(_translate("Dialog", "Evaluation Id", None))
        self.interactionIdLabel.setText(_translate("Dialog", "Interaction Id", None))
        self.sessionIdLabel.setText(_translate("Dialog", "Session Id", None))
        self.label_2.setText(_translate("Dialog", "Group Eval Id", None))
        self.label_4.setText(_translate("Dialog", "Meeting Id", None))
        self.label.setText(_translate("Dialog", "System Variable Control", None))
        self.pushButton.setText(_translate("Dialog", "Reset", None))

