# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/activities_Manager.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1433, 855)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(230, 10, 631, 241))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.activity = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.activity.setFont(font)
        self.activity.setObjectName(_fromUtf8("activity"))
        self.gridLayout_2.addWidget(self.activity, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.created_date = QtGui.QDateEdit(self.frame)
        self.created_date.setEnabled(False)
        self.created_date.setObjectName(_fromUtf8("created_date"))
        self.gridLayout_2.addWidget(self.created_date, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 3, 1, 1)
        self.created_lineEdit = QtGui.QLineEdit(self.frame)
        self.created_lineEdit.setEnabled(False)
        self.created_lineEdit.setObjectName(_fromUtf8("created_lineEdit"))
        self.gridLayout_2.addWidget(self.created_lineEdit, 3, 4, 1, 1)
        self.edited_date = QtGui.QDateEdit(self.frame)
        self.edited_date.setEnabled(False)
        self.edited_date.setObjectName(_fromUtf8("edited_date"))
        self.gridLayout_2.addWidget(self.edited_date, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 4, 3, 1, 1)
        self.edited_lineEdit = QtGui.QLineEdit(self.frame)
        self.edited_lineEdit.setEnabled(False)
        self.edited_lineEdit.setObjectName(_fromUtf8("edited_lineEdit"))
        self.gridLayout_2.addWidget(self.edited_lineEdit, 4, 4, 1, 1)
        self.name_lineEdit = QtGui.QLineEdit(self.frame)
        self.name_lineEdit.setEnabled(False)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.gridLayout_2.addWidget(self.name_lineEdit, 0, 1, 1, 4)
        self.desc_lineEdit = QtGui.QLineEdit(self.frame)
        self.desc_lineEdit.setEnabled(False)
        self.desc_lineEdit.setObjectName(_fromUtf8("desc_lineEdit"))
        self.gridLayout_2.addWidget(self.desc_lineEdit, 1, 1, 1, 4)
        self.path_lineEdit = QtGui.QLineEdit(self.frame)
        self.path_lineEdit.setEnabled(False)
        self.path_lineEdit.setObjectName(_fromUtf8("path_lineEdit"))
        self.gridLayout_2.addWidget(self.path_lineEdit, 2, 1, 1, 4)
        self.widget = QtGui.QWidget(self.frame)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_3 = QtGui.QPushButton(self.widget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_2.addWidget(self.widget, 5, 4, 1, 1)
        self.modules_tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.modules_tabWidget.setEnabled(False)
        self.modules_tabWidget.setGeometry(QtCore.QRect(10, 270, 1401, 531))
        self.modules_tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.modules_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.modules_tabWidget.setIconSize(QtCore.QSize(50, 20))
        self.modules_tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.modules_tabWidget.setObjectName(_fromUtf8("modules_tabWidget"))
        self.tab_diag = QtGui.QWidget()
        self.tab_diag.setObjectName(_fromUtf8("tab_diag"))
        self.label_9 = QtGui.QLabel(self.tab_diag)
        self.label_9.setGeometry(QtCore.QRect(40, 20, 101, 41))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_diag)
        self.label_10.setGeometry(QtCore.QRect(50, 60, 181, 41))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_diag)
        self.label_11.setGeometry(QtCore.QRect(50, 110, 111, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_diag)
        self.label_12.setGeometry(QtCore.QRect(50, 150, 111, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.comboBox = QtGui.QComboBox(self.tab_diag)
        self.comboBox.setGeometry(QtCore.QRect(140, 150, 71, 24))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.dialog_tabWidget = QtGui.QTabWidget(self.tab_diag)
        self.dialog_tabWidget.setGeometry(QtCore.QRect(400, 30, 831, 331))
        self.dialog_tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.dialog_tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.dialog_tabWidget.setObjectName(_fromUtf8("dialog_tabWidget"))
        self.questions_tab = QtGui.QWidget()
        self.questions_tab.setObjectName(_fromUtf8("questions_tab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.questions_tab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.questions_tableWidget = QtGui.QTableWidget(self.questions_tab)
        self.questions_tableWidget.setObjectName(_fromUtf8("questions_tableWidget"))
        self.questions_tableWidget.setColumnCount(2)
        self.questions_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.questions_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.questions_tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_7.addWidget(self.questions_tableWidget, 3, 0, 1, 9)
        self.loadQuestions_Button = QtGui.QPushButton(self.questions_tab)
        self.loadQuestions_Button.setObjectName(_fromUtf8("loadQuestions_Button"))
        self.gridLayout_7.addWidget(self.loadQuestions_Button, 0, 5, 1, 1)
        self.insertQuestion_Button = QtGui.QPushButton(self.questions_tab)
        self.insertQuestion_Button.setObjectName(_fromUtf8("insertQuestion_Button"))
        self.gridLayout_7.addWidget(self.insertQuestion_Button, 0, 0, 1, 1)
        self.clearQuestions_Button = QtGui.QPushButton(self.questions_tab)
        self.clearQuestions_Button.setObjectName(_fromUtf8("clearQuestions_Button"))
        self.gridLayout_7.addWidget(self.clearQuestions_Button, 0, 2, 1, 1)
        self.saveQuestions_Button = QtGui.QPushButton(self.questions_tab)
        self.saveQuestions_Button.setObjectName(_fromUtf8("saveQuestions_Button"))
        self.gridLayout_7.addWidget(self.saveQuestions_Button, 0, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(337, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 3, 1, 1)
        self.dialog_tabWidget.addTab(self.questions_tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.dialog_tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.modules_tabWidget.addTab(self.tab_diag, _fromUtf8(""))
        self.tab_vision = QtGui.QWidget()
        self.tab_vision.setObjectName(_fromUtf8("tab_vision"))
        self.frame_4 = QtGui.QFrame(self.tab_vision)
        self.frame_4.setGeometry(QtCore.QRect(20, 10, 381, 301))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spc_cd = QtGui.QLCDNumber(self.frame_4)
        self.spc_cd.setObjectName(_fromUtf8("spc_cd"))
        self.gridLayout.addWidget(self.spc_cd, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.frame_4)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.frame_4)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.frame_4)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.total_classes = QtGui.QLCDNumber(self.frame_4)
        self.total_classes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.total_classes.setObjectName(_fromUtf8("total_classes"))
        self.gridLayout.addWidget(self.total_classes, 2, 1, 1, 1)
        self.deleteDbButton = QtGui.QPushButton(self.frame_4)
        self.deleteDbButton.setObjectName(_fromUtf8("deleteDbButton"))
        self.gridLayout.addWidget(self.deleteDbButton, 9, 1, 1, 1)
        self.buildTreeButton = QtGui.QPushButton(self.frame_4)
        self.buildTreeButton.setObjectName(_fromUtf8("buildTreeButton"))
        self.gridLayout.addWidget(self.buildTreeButton, 5, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.frame_4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 4, 0, 1, 1)
        self.augButton = QtGui.QPushButton(self.frame_4)
        self.augButton.setObjectName(_fromUtf8("augButton"))
        self.gridLayout.addWidget(self.augButton, 4, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.frame_4)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 9, 0, 1, 1)
        self.increaseDbButton = QtGui.QPushButton(self.frame_4)
        self.increaseDbButton.setObjectName(_fromUtf8("increaseDbButton"))
        self.gridLayout.addWidget(self.increaseDbButton, 8, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.frame_4)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 8, 0, 1, 1)
        self.widget_2 = QtGui.QWidget(self.frame_4)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.formLayout = QtGui.QFormLayout(self.widget_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.classes_label = QtGui.QLabel(self.widget_2)
        self.classes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.classes_label.setObjectName(_fromUtf8("classes_label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.classes_label)
        self.label_13 = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_13)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 2)
        self.frame_2 = QtGui.QFrame(self.tab_vision)
        self.frame_2.setGeometry(QtCore.QRect(890, 10, 501, 301))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.tabWidget_classifiers = QtGui.QTabWidget(self.frame_2)
        self.tabWidget_classifiers.setGeometry(QtCore.QRect(10, 30, 481, 248))
        self.tabWidget_classifiers.setObjectName(_fromUtf8("tabWidget_classifiers"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget_3 = QtGui.QWidget(self.tab)
        self.widget_3.setGeometry(QtCore.QRect(20, 20, 148, 201))
        self.widget_3.setMinimumSize(QtCore.QSize(148, 201))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_24 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 2)
        self.label_21 = QtGui.QLabel(self.widget_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 1, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.widget_3)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.widget_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 2, 0, 1, 1)
        self.epoch_Box = QtGui.QSpinBox(self.widget_3)
        self.epoch_Box.setMaximum(1000)
        self.epoch_Box.setProperty("value", 50)
        self.epoch_Box.setObjectName(_fromUtf8("epoch_Box"))
        self.gridLayout_4.addWidget(self.epoch_Box, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.widget_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 3, 0, 1, 1)
        self.steps_Box = QtGui.QSpinBox(self.widget_3)
        self.steps_Box.setMinimum(1)
        self.steps_Box.setMaximum(90000)
        self.steps_Box.setSingleStep(100)
        self.steps_Box.setProperty("value", 1000)
        self.steps_Box.setObjectName(_fromUtf8("steps_Box"))
        self.gridLayout_4.addWidget(self.steps_Box, 3, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.widget_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 4, 0, 1, 1)
        self.cnn_accuracy_label = QtGui.QLabel(self.widget_3)
        self.cnn_accuracy_label.setText(_fromUtf8(""))
        self.cnn_accuracy_label.setObjectName(_fromUtf8("cnn_accuracy_label"))
        self.gridLayout_4.addWidget(self.cnn_accuracy_label, 4, 1, 1, 1)
        self.train_cnn_Button = QtGui.QPushButton(self.widget_3)
        self.train_cnn_Button.setObjectName(_fromUtf8("train_cnn_Button"))
        self.gridLayout_4.addWidget(self.train_cnn_Button, 5, 0, 1, 2)
        self.frame_7 = QtGui.QFrame(self.tab)
        self.frame_7.setGeometry(QtCore.QRect(210, 10, 241, 191))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.tabWidget_classifiers.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget_classifiers.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget_classifiers.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget_classifiers.addTab(self.tab_4, _fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 471, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame_5 = QtGui.QFrame(self.tab_vision)
        self.frame_5.setGeometry(QtCore.QRect(550, 10, 271, 301))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pic_4 = QtGui.QFrame(self.frame_5)
        self.pic_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pic_4.setFrameShadow(QtGui.QFrame.Raised)
        self.pic_4.setObjectName(_fromUtf8("pic_4"))
        self.gridLayout_5.addWidget(self.pic_4, 2, 1, 1, 1)
        self.pic_3 = QtGui.QFrame(self.frame_5)
        self.pic_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pic_3.setFrameShadow(QtGui.QFrame.Raised)
        self.pic_3.setObjectName(_fromUtf8("pic_3"))
        self.gridLayout_5.addWidget(self.pic_3, 2, 0, 1, 1)
        self.pic_2 = QtGui.QFrame(self.frame_5)
        self.pic_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pic_2.setFrameShadow(QtGui.QFrame.Raised)
        self.pic_2.setObjectName(_fromUtf8("pic_2"))
        self.gridLayout_5.addWidget(self.pic_2, 1, 1, 1, 1)
        self.pic_1 = QtGui.QFrame(self.frame_5)
        self.pic_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pic_1.setFrameShadow(QtGui.QFrame.Raised)
        self.pic_1.setObjectName(_fromUtf8("pic_1"))
        self.gridLayout_6 = QtGui.QGridLayout(self.pic_1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_26 = QtGui.QLabel(self.pic_1)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.pic_1, 1, 0, 1, 1)
        self.pic_6 = QtGui.QFrame(self.frame_5)
        self.pic_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pic_6.setFrameShadow(QtGui.QFrame.Raised)
        self.pic_6.setObjectName(_fromUtf8("pic_6"))
        self.gridLayout_5.addWidget(self.pic_6, 3, 1, 1, 1)
        self.pic_5 = QtGui.QFrame(self.frame_5)
        self.pic_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pic_5.setFrameShadow(QtGui.QFrame.Raised)
        self.pic_5.setObjectName(_fromUtf8("pic_5"))
        self.gridLayout_5.addWidget(self.pic_5, 3, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 0, 0, 1, 2)
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.frame_5.raise_()
        self.label_20.raise_()
        self.modules_tabWidget.addTab(self.tab_vision, _fromUtf8(""))
        self.tab_adapt = QtGui.QWidget()
        self.tab_adapt.setObjectName(_fromUtf8("tab_adapt"))
        self.modules_tabWidget.addTab(self.tab_adapt, _fromUtf8(""))
        self.tab_reports = QtGui.QWidget()
        self.tab_reports.setObjectName(_fromUtf8("tab_reports"))
        self.tableView = QtGui.QTableView(self.tab_reports)
        self.tableView.setGeometry(QtCore.QRect(290, 70, 941, 391))
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.reportLoadButton = QtGui.QPushButton(self.tab_reports)
        self.reportLoadButton.setGeometry(QtCore.QRect(290, 20, 110, 29))
        self.reportLoadButton.setObjectName(_fromUtf8("reportLoadButton"))
        self.writeReportButton = QtGui.QPushButton(self.tab_reports)
        self.writeReportButton.setGeometry(QtCore.QRect(420, 20, 110, 29))
        self.writeReportButton.setObjectName(_fromUtf8("writeReportButton"))
        self.modules_tabWidget.addTab(self.tab_reports, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.modules_tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 191, 241))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.newButton = QtGui.QPushButton(self.frame_3)
        self.newButton.setObjectName(_fromUtf8("newButton"))
        self.gridLayout_3.addWidget(self.newButton, 0, 0, 1, 1)
        self.loadactButton = QtGui.QPushButton(self.frame_3)
        self.loadactButton.setObjectName(_fromUtf8("loadactButton"))
        self.gridLayout_3.addWidget(self.loadactButton, 1, 0, 1, 1)
        self.editButton = QtGui.QPushButton(self.frame_3)
        self.editButton.setEnabled(False)
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.gridLayout_3.addWidget(self.editButton, 2, 0, 1, 1)
        self.exitButton = QtGui.QPushButton(self.frame_3)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.gridLayout_3.addWidget(self.exitButton, 3, 0, 1, 1)
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(900, 10, 351, 251))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_27 = QtGui.QLabel(self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(40, 0, 261, 251))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1433, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.modules_tabWidget.setCurrentIndex(1)
        self.dialog_tabWidget.setCurrentIndex(0)
        self.tabWidget_classifiers.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Description", None))
        self.activity.setText(_translate("MainWindow", "Activity", None))
        self.label_2.setText(_translate("MainWindow", "Path", None))
        self.label_4.setText(_translate("MainWindow", "Created in", None))
        self.label_5.setText(_translate("MainWindow", "Last Edit", None))
        self.label_6.setText(_translate("MainWindow", "Created by", None))
        self.label_7.setText(_translate("MainWindow", "Edited by", None))
        self.pushButton_3.setText(_translate("MainWindow", "Cancel", None))
        self.pushButton_2.setText(_translate("MainWindow", "Ok", None))
        self.label_9.setText(_translate("MainWindow", "Edit doubt wrods", None))
        self.label_10.setText(_translate("MainWindow", "View dialogue files", None))
        self.label_11.setText(_translate("MainWindow", "Create dialogues", None))
        self.label_12.setText(_translate("MainWindow", "Choose SR", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Google", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "NAO", None))
        item = self.questions_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Questions", None))
        item = self.questions_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Answers", None))
        self.loadQuestions_Button.setText(_translate("MainWindow", "Load File", None))
        self.insertQuestion_Button.setText(_translate("MainWindow", "Insert Question", None))
        self.clearQuestions_Button.setText(_translate("MainWindow", "Clear Table", None))
        self.saveQuestions_Button.setText(_translate("MainWindow", "Save", None))
        self.dialog_tabWidget.setTabText(self.dialog_tabWidget.indexOf(self.questions_tab), _translate("MainWindow", "Default Questions", None))
        self.dialog_tabWidget.setTabText(self.dialog_tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Dialogue Files", None))
        self.modules_tabWidget.setTabText(self.modules_tabWidget.indexOf(self.tab_diag), _translate("MainWindow", "Dialogue", None))
        self.label_16.setText(_translate("MainWindow", "Perform dataAug", None))
        self.label_19.setText(_translate("MainWindow", "Samples per Class", None))
        self.label_15.setText(_translate("MainWindow", "Total Classes", None))
        self.label_3.setText(_translate("MainWindow", "Database Information", None))
        self.deleteDbButton.setText(_translate("MainWindow", "Go!", None))
        self.buildTreeButton.setText(_translate("MainWindow", "Go!", None))
        self.label_14.setText(_translate("MainWindow", "Build Tree Directories", None))
        self.augButton.setText(_translate("MainWindow", "Go!", None))
        self.label_18.setText(_translate("MainWindow", "Delete Database", None))
        self.increaseDbButton.setText(_translate("MainWindow", "Go!", None))
        self.label_17.setText(_translate("MainWindow", "Increase Database", None))
        self.classes_label.setText(_translate("MainWindow", "<< CLASSES>>", None))
        self.label_13.setText(_translate("MainWindow", "Classes", None))
        self.label_24.setText(_translate("MainWindow", "Parameters", None))
        self.label_21.setText(_translate("MainWindow", "Batch Size", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "4", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "8", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "16", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "32", None))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "64", None))
        self.label_22.setText(_translate("MainWindow", "Epochs", None))
        self.label_23.setText(_translate("MainWindow", "Steps", None))
        self.label_25.setText(_translate("MainWindow", "Accuracy", None))
        self.train_cnn_Button.setText(_translate("MainWindow", "Train Model", None))
        self.tabWidget_classifiers.setTabText(self.tabWidget_classifiers.indexOf(self.tab), _translate("MainWindow", "CNN", None))
        self.tabWidget_classifiers.setTabText(self.tabWidget_classifiers.indexOf(self.tab_2), _translate("MainWindow", "KNN", None))
        self.tabWidget_classifiers.setTabText(self.tabWidget_classifiers.indexOf(self.tab_3), _translate("MainWindow", "MLP", None))
        self.tabWidget_classifiers.setTabText(self.tabWidget_classifiers.indexOf(self.tab_4), _translate("MainWindow", "SVM", None))
        self.label_8.setText(_translate("MainWindow", "Classifiers Settings", None))
        self.label_26.setText(_translate("MainWindow", "Img0", None))
        self.label_20.setText(_translate("MainWindow", "Samples", None))
        self.modules_tabWidget.setTabText(self.modules_tabWidget.indexOf(self.tab_vision), _translate("MainWindow", "Vision", None))
        self.modules_tabWidget.setTabText(self.modules_tabWidget.indexOf(self.tab_adapt), _translate("MainWindow", "Adaption", None))
        self.reportLoadButton.setText(_translate("MainWindow", "Load", None))
        self.writeReportButton.setText(_translate("MainWindow", "Save", None))
        self.modules_tabWidget.setTabText(self.modules_tabWidget.indexOf(self.tab_reports), _translate("MainWindow", "System Reports", None))
        self.modules_tabWidget.setTabText(self.modules_tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Evaluations", None))
        self.newButton.setText(_translate("MainWindow", "New Activity", None))
        self.newButton.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.loadactButton.setText(_translate("MainWindow", "Load Activity", None))
        self.loadactButton.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.editButton.setText(_translate("MainWindow", "Edit", None))
        self.editButton.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.exitButton.setText(_translate("MainWindow", "Exit", None))
        self.exitButton.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imgs/pencil.png\"/></p></body></html>", None))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

from GUI import imgs
